# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-22 16:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=30)),
                ('post', tinymce.models.HTMLField()),
                ('image_caption', models.CharField(max_length=30)),
                ('post_image', models.ImageField(default='card', upload_to='post/')),
                ('owner', models.ForeignKey(default='Brian', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['image_name'],
            },
        ),
    ]
