# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-22 16:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0002_remove_image_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['owner']},
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_name',
        ),
    ]
