# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-22 11:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0002_auto_20180722_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='owner',
        ),
    ]
