# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-22 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0003_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='owner',
            field=models.CharField(default='Sigila', max_length=20),
        ),
    ]
