# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-22 11:40
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0004_auto_20180722_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='post',
            field=tinymce.models.HTMLField(),
        ),
    ]
