# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-22 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0006_auto_20180722_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='owner',
            field=models.CharField(default='Sigila', max_length=20),
        ),
        migrations.AddField(
            model_name='image',
            name='post_image',
            field=models.ImageField(default='card', upload_to='post/'),
        ),
    ]
