# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-23 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0007_auto_20180723_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='comment',
            field=models.CharField(blank=True, default='Comment', max_length=30),
        ),
    ]
