# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-22 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0007_auto_20180722_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='post_image',
            field=models.ImageField(upload_to='post/'),
        ),
    ]
