# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-22 18:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0007_auto_20180722_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='comments',
            field=models.ForeignKey(default='Comment', on_delete=django.db.models.deletion.CASCADE, to='insta.Comments'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.CharField(default='Comment', max_length=30),
        ),
        migrations.AlterField(
            model_name='image',
            name='owner',
            field=models.ForeignKey(default='Brian', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
