# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-23 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0008_image_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='comments',
            new_name='image',
        ),
        migrations.AddField(
            model_name='comments',
            name='comment',
            field=models.TextField(default='Trie'),
        ),
    ]
