# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-22 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0011_auto_20180722_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_caption',
            field=models.CharField(max_length=30),
        ),
    ]
