# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-23 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0012_auto_20180723_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='image_id',
            field=models.TextField(default='Noo'),
        ),
    ]
