# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-26 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0021_auto_20180726_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comment_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='image_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
