# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-27 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0023_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='total_likes',
            field=models.IntegerField(default=0),
        ),
    ]
