# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-30 05:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0024_like_total_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='comment_date',
        ),
    ]
