# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-30 05:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0025_remove_comments_comment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_date',
        ),
    ]
